Remove redundant method defs
astroquery/utils/tap/core.py:1994:5: F811 redefinition of unused 'login' from line 1354
astroquery/utils/tap/core.py:2033:5: F811 redefinition of unused 'login_gui' from line 1393
astroquery/utils/tap/core.py:2053:5: F811 redefinition of unused '__dologin' from line 1413
astroquery/utils/tap/core.py:2072:5: F811 redefinition of unused 'logout' from line 1428